Command to toggle issuing AoC completionist
python-discord/sir-robin pull request #112
Opened 2024-01-28 13:27 UTC by ChrisLovering

This adds a new command, and redis cache, to control whether the AoC completionist role is issued.

This also refactors the cog a little it while I am there.

Adding a do not merge to this PR as I will need to migrate redis caches to the new namespaces before merging this.

2024-01-31 02:55 UTC, janine9vn requested changes
If the role from the loaded in config can't be found, then the `&aoc ct` to do the initial toggle-on fails. I think it would be better to output the error somewhere visible for admins/the Event Runner to see if this occurs. It does get logged, but it wouldn't be obvious for a few minutes that something was wrong and to check the logs. I think outputting to devlog like we do for leaderboard errors makes sense.

Otherwise everything works well and as expected. I wasn't able to test the scheduler changes, but I can also worry about it in 11 months.

2024-01-31 09:52 UTC, ChrisLovering commented
> If the role from the loaded in config can't be found, then the `&aoc ct` to do the initial toggle-on fails. I think it would be better to output the error somewhere visible for admins/the Event Runner to see if this occurs. It does get logged, but it wouldn't be obvious for a few minutes that something was wrong and to check the logs. I think outputting to devlog like we do for leaderboard errors makes sense.
> 
> Otherwise everything works well and as expected. I wasn't able to test the scheduler changes, but I can also worry about it in 11 months.

It's a warning log that will be pushed to sentry, and output to #dev-alerts, like most other problems like this in our other bots

2024-01-31 16:28 UTC, janine9vn approved these changes

2024-02-01 09:00 UTC, shtlrs approved these changes

2024-02-01 09:10 UTC, ChrisLovering commented on bot/exts/advent_of_code/_cog.py
> +    @with_role(Roles.admins, fail_silently=True)
Yea toggling twice was my thought, since it's rarely going to happen anyway.

2024-02-01 09:13 UTC, ChrisLovering commented
Just realised I never gave event leads access to run this command, added a small commit to fix this.

2024-02-01 11:13 UTC, merged